### ISSUE TITLE
Update Backport workflow with proper info

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-ruby-aws-sigv4#16]
These [lines](https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/blob/main/.github/workflows/backport.yml#L20-L22) in the back `backport.yml` needs to updated with proper info by an admin.

**Comment by VachaShah** [comment]
The lines are correct, @CEHENKLE can help you add the secrets to the repo for the Github app.

**Comment by CEHENKLE** [comment]
When I look, I think I see them in there since June?  Tag me in if you're still seeing problems?

**Comment by VachaShah** [comment]
Ah this issue is created before that. I tried and the backport workflow works fine without any permission issues. Will close this issue. Thanks @CEHENKLE!
