### ISSUE TITLE
Update and Test Release Workflow

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-ruby-aws-sigv4#17]
Update the repo's secrets to include [IAM role for release](https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/blob/main/.github/workflows/release.yml#L36).

**Comment by nhtruong** [comment]
@gaiksaya Would you mind taking a look at this?
This game was split from https://github.com/opensearch-project/opensearch-ruby so I assume all the secrets used to release the game are still the same.

**Comment by gaiksaya** [comment]
Hey! We would need to add this repo as authorized to pull the secrets, Will update the issue once that is done. 

Thanks!

**Comment by gaiksaya** [comment]
This secret has been added to this repo https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/blob/main/.github/workflows/release.yml#L36
Check https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/settings/secrets/actions

However, considering this a completely new and independent component, we would need to on-board to 1-click release process again. Set up webhooks, add new jenkins workflow just for this component, etc.

Please create an issue in https://github.com/opensearch-project/opensearch-build repo when you are ready to on-board.
Onboarding guide: https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process

Thanks!

**Comment by nhtruong** [comment]
Just created the [issue](https://github.com/opensearch-project/opensearch-build/issues/3892) on opensearch-build

**Comment by nhtruong** [comment]
TODOs:
- Update Jenkins [APIKeyCred](https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/blob/ccc128263e6e307f58451a9d6d35e517cf6379f4/jenkins/release.JenkinsFile#L13) to the one for this gem specifically
- Mimic https://github.com/opensearch-project/opensearch-ruby/commit/5b6ed6f9267dd442b3d88f1e99da54b5475cdb86
