### ISSUE TITLE
[PROPOSAL] Make the gem compatible with Ruby 2.4

### ISSUE THREAD

**Issue by dla-c-box** [opensearch-project/opensearch-ruby-aws-sigv4#19]
### What are you proposing?
Make the gem compatible with Ruby 2.4.

### What problems are you trying to solve?
We want to upgrade a system from ElasticSearch to AWS managed OpenSearch.  Upgrading Ruby first causes other compatibility issues and could delay the migration to AWS managed OpenSearch (which we would otherwise begin in the coming days).

### Any remaining open questions?
From what I see, the source code of opensearch-ruby-aws-sigv4 is pretty much a ~100 lines of code wrapper around other ruby gems that support Ruby >= 2.4.  [aws-sigv4](https://rubygems.org/gems/aws-sigv4) requires Ruby >= 2.3 and [opensearch-ruby](https://rubygems.org/gems/opensearch-ruby) requires Ruby >= 2.4.  Is there any reason why we wouldn't want opensearch-ruby-aws-sigv4 to run on Ruby 2.4? (i.e. is there a specific reason why you picked Ruby 2.5 to wrap the features of those other gems, e.g. is there any feature lacking from Ruby 2.4 to achieve this like some underlying compatibility issue with the communication with AWS, or was it just e.g. because you only had Ruby 2.5 to test with?)

**Comment by dblock** [comment]
I don't see any reason why not. Want to try and PR adding Ruby 2.4 to CI/CD and lowering `s.required_ruby_version = '>= 2.5'` in .gemspec?
